### ISSUE TITLE
Bitcoin::Crypto deprecation warnings

### ISSUE THREAD

**Issue by bbrtj** [chromatic/dogecoin-tricks-book#1]
This book uses Bitcoin::Crypto perl module in an example in section `Make Keys from Answers`. There was a major release in october which deprecated some symbols. The example is affected and will now be issuing deprecation warnings if someone runs it with the newest version.

The deprecated methods are not going away for a long time, but you may want to modify the example accordingly. In this case, seems like it would involve changing `$package->from_bytes($bytestr)` to `$package->from_serialized($bytestr)` (https://metacpan.org/pod/Bitcoin::Crypto::Key::Private#from_serialized). This got deprecated in version `2.000`.

Cheers.

**Comment by chromatic** [comment]
Thank you, Bartosz! I'll make that change.

**Comment by chromatic** [comment]
I've just committed this change to the main branch. Thank you again for reporting!
